version: '3.8'
services:
  db:
    build: 
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: db
    ports:
      - 3060:3306
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
      - TZ=UTC
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/store:/var/lib/mysql
      - ./db/logs:/var/log/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
  server:
    build: 
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: server
    ports:
      - 8000:8000
    tty: true
    #volumes:
    #  - ./server:/go/src/server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - 'db'
  client:
    build: 
      context: .
      dockerfile: ./docker/client/Dockerfile
    container_name: client
    ports:
      - 3000:3000
    tty: true
    #volumes:
    #  - ./client:/src/client
    depends_on:
      - 'server'
  nginx:
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
    tty: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - 'client'
